export { default as EventsWidget } from './EventsWidget';
export { default as MembershipFeeWidget } from './MembershipFeeWidget';
export { default as TasksWidget } from './TasksWidget';
export { default as ActivityWidget } from './ActivityWidget';
export { default as MessagesWidget } from './MessagesWidget';
export { default as ShopWidget } from './ShopWidget';
export { default as AnnouncementsWidget } from './AnnouncementsWidget';
export { default as UsersStatsWidget } from './UsersStatsWidget';
export { default as PrayerTimesWidget } from './PrayerTimesWidget';
export { default as WorkGroupsWidget } from './WorkGroupsWidget';
export { DocumentsWidget, SettingsWidget, GuideWidget, ImamQAWidget } from './QuickLinkWidget';
export { widgetRegistry, getWidgetById, getDefaultLayout } from './WidgetRegistry';
